# Generated by Django 4.2.7 on 2023-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropsdata',
            old_name='moisture',
            new_name='humidity',
        ),
        migrations.AddField(
            model_name='cropsdata',
            name='ldr',
            field=models.FloatField(null=True),
        ),
    ]
